In [1]:
import numpy as np

In [23]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [30]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [33]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [36]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
a_centered_sp

8.0